name: backend

on:
  push:
    branches:
      - main

  schedule:
    # 9時間を足して、日本時間で毎日21時に実行
    - cron: '0 12 * * *'

defaults:
  run:
    working-directory: backend

jobs: # workflow 内で実行されるジョブの集合を定義
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 # GitHubリポジトリのコードをGitHub Actionsのランナーにチェックアウト
      - uses: actions/setup-node@v3 # Node.jsをGitHub Actionsのランナーにセットアップする
        with:
          node-version: 16.x # セットアップするNode.jsのバージョンを指定(16系の最新版)

      - run: npm ci
      - run: npm run test -- --coverage
      - run: npm run build

      - run: node dist/index.js &
      - run: npm run test:api

      - uses: actions/upload-artifact@v3 # ビルドやテストの結果をアーティファクトとして保存するためのアクション
        if: always()
        with:
          name: coverage # アーティファクトの名前を指定
          path: backend/coverage/** # アーティファクトとして保存するファイルやディレクトリのパスを指定
          retention-days: 5 # アーティファクトを保存する日数を指定(5日間)

      - uses: actions/upload-artifact@v3
        with:
          name: dist
          path: backend/dist/index.js
          retention-days: 5